In [28]:
import numpy as np

def game(players):
    
    board = np.zeros((4,4), dtype = int) - 1
    win = 0
    
    while win != 1:
        for i in range(0,4):
            #input()
            board = play(i, board, "random")
            print(board)
            if sum(board[i,:]) == 118:
                win = 1
        
        

    
    

In [29]:
game(1)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 8 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 8 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 8 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [ 8 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 -1 -1 -1]
 [-1 -1 -1 -1]]
[[-1 -1 -1 -1]
 [-1 -1 -

In [27]:
def play(player, board, strategy):
    transformBoard(player, board)
    strategies = {"random": np.random.random(10)}
    dice = np.random.randint(1,7)
    moves = playableMoves(board, dice, player)
    
    if np.sum(moves) == 0:
        reverseBoard(player, board)
        return board
    
    util = utility(board, moves, dice)
    score = list(np.dot(strategies[strategy], util))
    move = score.index(max(score))
    
    newBoard(board, move, dice, player)
    reverseBoard(player, board)
    
    if dice == 6:
        play(player, board, strategy)
    
    return board

In [6]:
board = np.zeros((4,4), dtype = int) - 1
board[0,:] = [31, 2, 0, -1]
board[1,:] = [27, 10, -1, -1]
board[2,:] = [4, 1, -1, -1]
board[3,:] = [23, -1, -1, -1]
print(board)
transformBoard(2, board)
print(board)
reverseBoard(2, board)
print(board)

[[31  2  0 -1]
 [27 10 -1 -1]
 [ 4  1 -1 -1]
 [23 -1 -1 -1]]


NameError: name 'transformBoard' is not defined

In [7]:
print(playableMoves(board, 3, 2))

NameError: name 'playableMoves' is not defined

In [8]:
def newBoard(board, move, dice, player):
    if board[player, move] == -1:
        board[player, move] = 0
    else:
        board[player, move] += dice
    
    for i in range(0,4):
        for j in range(0, 4):
            if i != player:
                if board[i,j] == board[player, move] and board[i,j] < 28: 
                    board[i,j] = -1

In [9]:
def reverseBoard(player, board):
    oldBoard = np.array(board)
    for i in range(0,3):
        board[(player + i + 1) % 4,:] = (board[(player + i + 1) % 4,:] - 7 * (i+1)) % 28  
    for i in range(0,4):
        for j in range(0,4):
            if(oldBoard[i,j] == -1 or oldBoard[i,j] > 27):
                board[i,j] = oldBoard[i,j]

In [11]:
def transformBoard(player, board):
    oldBoard = np.array(board)
    for i in range(0,3):
        board[(player + i + 1) % 4,:] = (board[(player + i + 1) % 4,:] + 7 * (i+1)) % 28  
    for i in range(0,4):
        for j in range(0,4):
            if(oldBoard[i,j] == -1 or oldBoard[i,j] > 27):
                board[i,j] = oldBoard[i,j]

In [12]:
print(board)
print(board)

[[31  2  0 -1]
 [27 10 -1 -1]
 [11  1 -1 -1]
 [23 -1 -1 -1]]
[[31  2  0 -1]
 [27 10 -1 -1]
 [11  1 -1 -1]
 [23 -1 -1 -1]]


In [13]:
def playableMoves(board, dice, player):
    moves = np.array([0,0,0,0])
    for i in range(0, 4):
        if len(np.where(board[player,:] == board[player,i] + dice)[0]) == 0 and board[player, i] + dice < 32 and board[player, i] != -1:
            moves[i] = 1
        else:
            moves[i] = 0
        if dice == 6 and len(np.where(board[player,:] == 0)[0]) == 0 and board[player, i] == -1:
            moves[i] = 1
        
    return moves

In [14]:
def utility(board, moves, dice):
    utils = np.ones((10,4), dtype = float)
    for i in range(0, 10):
        utils[i,:] = moves
    return utils

In [15]:
def strategy(strat):
    return 1

In [16]:
board = np.zeros((4,4), dtype = int) - 1
board[0,:] = [31, 2, 0, -1]
board[1,:] = [27, 10, -1, -1]
board[2,:] = [4, 1, -1, -1]
board[3,:] = [23, -1, -1, -1]

board[0,2] = 2
#len(np.where(board[0,:] == 0))
board
print(move)

NameError: name 'move' is not defined

In [17]:
def strategy(board, possible, dice):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-17-acf6b409c256>, line 2)

In [18]:
np.random.random(10)

array([ 0.99117463,  0.12101541,  0.24871104,  0.35526835,  0.84828244,
        0.05332505,  0.09299109,  0.64270532,  0.25038011,  0.33539035])

In [19]:
board.isEmpty()

AttributeError: 'numpy.ndarray' object has no attribute 'isEmpty'